[package]
name = "turbo_plugin_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "turbo_plugin_python"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = "0.20.3"

[features]
extension-module = ["pyo3/extension-module"]
