[package]
name = "turbo_audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.14.0"
websocket = "0.24.0"
rand = "0.8"
warp = "0.3"
futures-util = "0.3.3"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
futures-cpupool = "0.1"


