[tasks.mkdir]
command = "mkdir"
args = ["-p", "../../bin"]

[tasks.rm]
command = "rm"
args = ["-f", "../../bin/libraindrop.so"]
dependencies = ["build-release", "mkdir"]

[tasks.build-debug]
command = "cargo"
args = ["build"]

[tasks.install-debug]
command = "cp"
args = ["target/debug/libraindrop.so", "../../bin"]
dependencies = ["build-debug", "mkdir", "rm"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.install-release]
command = "cp"
args = ["target/release/libraindrop.so",  "../../bin"]
dependencies = ["build-release", "mkdir", "rm"]
